"""
wire_gamemode.py — LONG-RUN DIRECTIVE L5.2
===========================================
Wires the runtime entry surface into BOTH day-one target levels:

    /Game/ASTRAWILD/Maps/Prototype/L_Proto_01         (fast sanity map)
    /Game/ASTRAWILD/Maps/L_Showcase_ArtOverhaul       (day-one finisher)

For each level:
  1. GameMode Override on WorldSettings — BP_AstrawildGameMode when
     setup_input_assets.py has run (pawn + input already bound on its CDO),
     otherwise the native AAstrawildGameMode (DefaultEngine.ini
     GlobalDefaultGameMode equivalent — zero-asset playable either way).
  2. Default-pawn verification — BP_AstrawildPlayer's generated class is
     checked on the game-mode CDO when the BP path is used.
  3. Input-context verification — IMC_Player / IMC_Gamepad assets must
     exist (warning when absent: the C++ runtime fallback still plays).
  4. DataTable surface check — DT_AstrawildAbilities / DT_AstrawildWeather /
     DT_AstrawildZones presence is verified (generated by
     generate_datatables.py; informational, the runtime registry remains
     the authority).

Idempotent: re-running re-asserts every binding (property sets converge).

UNVERIFIED — NEEDS MACHINE (R2/R3): authored against documented UE5 editor
Python surfaces; first engine run is the conformance test.

Run headless (Windows):
  "E:\\Epic Games\\UnrealEngine\\Engine\\Binaries\\Win64\\UnrealEditor-Cmd.exe" ^
    "E:\\AstrawildGame\\ASTRAWILD.uproject" ^
    -run=pythonscript -script="E:\\AstrawildGame\\Tools\\Python\\wire_gamemode.py" ^
    -stdout -unattended -nopause -nosplash
"""

import sys

import unreal

PREFIX = "[WireGM]"

LEVEL_PATHS = [
    "/Game/ASTRAWILD/Maps/Prototype/L_Proto_01",
    "/Game/ASTRAWILD/Maps/L_Showcase_ArtOverhaul",
]

BP_GAMEMODE = "/Game/ASTRAWILD/Blueprints/BP_AstrawildGameMode"
BP_PLAYER = "/Game/ASTRAWILD/Blueprints/BP_AstrawildPlayer"
IMC_PLAYER = "/Game/ASTRAWILD/Input/IMC_Player"
IMC_GAMEPAD = "/Game/ASTRAWILD/Input/IMC_Gamepad"
DATA_TABLES = [
    "/Game/ASTRAWILD/DataTables/DT_AstrawildAbilities",
    "/Game/ASTRAWILD/DataTables/DT_AstrawildWeather",
    "/Game/ASTRAWILD/DataTables/DT_AstrawildZones",
]


def log(message):
    unreal.log("{} {}".format(PREFIX, message))


def log_warn(message):
    unreal.log_warning("{} {}".format(PREFIX, message))


def _level_api():
    try:
        return unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem)
    except Exception:  # pragma: no cover — legacy engines only
        return unreal.EditorLevelLibrary


def safe_set_property(obj, property_name, value):
    try:
        obj.set_editor_property(property_name, value)
        return True
    except Exception as exc:  # noqa: BLE001 — resilience by design
        log_warn("could not set '{}' on {} ({})".format(
            property_name, obj.get_name(), exc))
        return False


def find_world_settings():
    world = _level_api().get_editor_world()
    try:
        settings = world.get_world_settings()
        if settings:
            return settings
    except Exception:
        pass
    return None


def resolve_game_mode_class():
    """BP game-mode when present; native class otherwise."""
    if unreal.EditorAssetLibrary.does_asset_exist(BP_GAMEMODE):
        cls = unreal.load_object(None, BP_GAMEMODE + ".BP_AstrawildGameMode_C")
        if cls is not None:
            return cls, "BP_AstrawildGameMode"
    return unreal.AstrawildGameMode, "native AAstrawildGameMode"


def verify_pawn_binding():
    if not unreal.EditorAssetLibrary.does_asset_exist(BP_PLAYER):
        log_warn("BP_AstrawildPlayer absent — native "
                 "AAstrawildPlayerCharacter (runtime input fallback) plays.")
        return False
    return True


def verify_input_contexts():
    missing = [p for p in (IMC_PLAYER, IMC_GAMEPAD)
               if not unreal.EditorAssetLibrary.does_asset_exist(p)]
    if missing:
        log_warn("input contexts missing (C++ runtime fallback still "
                 "authoritative): " + ", ".join(missing))
        return False
    log("Input contexts present: IMC_Player + IMC_Gamepad.")
    return True


def verify_data_tables():
    missing = [p for p in DATA_TABLES
               if not unreal.EditorAssetLibrary.does_asset_exist(p)]
    if missing:
        log_warn("DataTable assets missing (run generate_datatables.py): "
                 + ", ".join(missing))
        return False
    log("DataTable surface present: Abilities/Weather/Zones.")
    return True


def wire_level(level_path):
    log("--- wiring {} ---".format(level_path))
    level_api = _level_api()
    if unreal.EditorAssetLibrary.does_asset_exist(level_path):
        if not level_api.load_level(level_path):
            raise RuntimeError("Failed to load level: " + level_path)
        log("Loaded existing level.")
    else:
        if not level_api.new_level(level_path):
            raise RuntimeError("Failed to create level: " + level_path)
        log("Created new level (empty — build its content with "
            "build_prototype_map.py / build_showcase_map.py first).")

    settings = find_world_settings()
    if not settings:
        log_warn("WorldSettings not reachable — project-level "
                 "GlobalDefaultGameMode still applies.")
        return False

    game_mode_class, source = resolve_game_mode_class()
    if safe_set_property(settings, "default_game_mode", game_mode_class):
        log("GameMode Override = {} ({}).".format(
            game_mode_class.get_name(), source))

    verify_pawn_binding()
    verify_input_contexts()
    verify_data_tables()
    if not level_api.save_current_level():
        raise RuntimeError("Failed to save level: " + level_path)
    log("Level saved: " + level_path)
    return True


def main():
    log("=" * 60)
    log("ASTRAWILD GameMode/pawn/input wiring (both day-one levels)")
    log("=" * 60)
    failures = 0
    for level_path in LEVEL_PATHS:
        try:
            if not wire_level(level_path):
                failures += 1
        except Exception as exc:  # noqa: BLE001
            log_warn("wiring failed for {}: {}".format(level_path, exc))
            failures += 1
    if failures:
        log("VERDICT: PARTIAL — {} of {} levels wired; see warnings above."
            .format(len(LEVEL_PATHS) - failures, len(LEVEL_PATHS)))
        return
    log("VERDICT: PASS — both levels wired (GameMode override asserted; "
        "pawn/input/DataTable surfaces verified).")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:  # noqa: BLE001
        unreal.log_error("[WireGM] FAILED: {}".format(error))
        sys.exit(1)
