#!/usr/bin/env python3
"""
ASTRAWILD Batch 8 — "The Grand Menagerie" bestiary generator (deterministic).

Generates:
  1. Source/AstrawildCore/Private/AstrawildBestiaryData.cpp  (200 species rows)
  2. Docs/ASTRAWILD_BESTIARY_CODEX.md                        (full designed codex)

Design contract (Docs/ASTRAWILD_BESTIARY_CODEX.md is the human-readable mirror):
  - 12 zones x ~17 species = exactly 200 generated species (+10 hand-authored
    Batch 1-7 species = 210 total Echo species).
  - Every species carries: family, body plan, size class, element, weakness,
    role, home zone, personality, activity pattern, stat budget, capture
    difficulty, hostility, two tint colors (procedural body), diet, loot and
    work affinities — everything the runtime needs for a designed silhouette.
  - Deterministic: same input -> same output (no RNG, index math only).

Run:  python3 Scripts/generate_bestiary.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CPP_OUT = os.path.join(ROOT, "Source", "AstrawildCore", "Private", "AstrawildBestiaryData.cpp")
DOC_OUT = os.path.join(ROOT, "Docs", "ASTRAWILD_BESTIARY_CODEX.md")

GENERATION_NOTE = "Generated by Scripts/generate_bestiary.py (Batch 8) - DO NOT EDIT BY HAND. Re-run the script instead."

# ---------------------------------------------------------------------------
# Element system: three resonant opposition pairs. A species is WEAK to its
# opposite (x1.5 damage taken) and resists its own element (x0.8 baseline).
# ---------------------------------------------------------------------------
ELEMENTS = ["Light", "Ash", "Flora", "Ember", "Frost", "Pulse"]
WEAK_TO = {  # symmetric opposition pairs
    "Light": "Ash", "Ash": "Light",
    "Flora": "Ember", "Ember": "Flora",
    "Frost": "Pulse", "Pulse": "Frost",
}

# ---------------------------------------------------------------------------
# Zones: id, enum, display name, threat level, element flavor pool.
# ---------------------------------------------------------------------------
ZONES = [
    ("Zone_DawnFields",       "DawnFields",         "Dawn Fields",         1, ["Flora", "Light", "Pulse"]),
    ("Zone_DuskMarsh",        "DuskMarsh",          "Dusk Marsh",          2, ["Flora", "Ash", "Pulse"]),
    ("Zone_EmberRidge",       "EmberRidge",         "Ember Ridge",         3, ["Ember", "Ash", "Light"]),
    ("Zone_Frostveil",        "FrostveilExpanse",   "Frostveil Expanse",   3, ["Frost", "Light", "Pulse"]),
    ("Zone_Glimmerwood",      "Glimmerwood",        "Glimmerwood",         2, ["Light", "Pulse", "Flora"]),
    ("Zone_HollowApproach",   "HollowApproach",     "Hollow Approach",     4, ["Ash", "Pulse", "Ember"]),
    ("Zone_AzureShallows",    "AzureShallows",      "Azure Shallows",      2, ["Frost", "Pulse", "Light"]),
    ("Zone_TidebreakerIsles", "TidebreakerIsles",   "Tidebreaker Isles",   3, ["Pulse", "Frost", "Light"]),
    ("Zone_SunscarDesert",    "SunscarDesert",      "Sunscar Desert",      3, ["Ember", "Light", "Ash"]),
    ("Zone_Stormcrest",       "StormcrestHighlands","Stormcrest Highlands",3, ["Pulse", "Frost", "Ash"]),
    ("Zone_VerdantReach",     "VerdantReach",       "Verdant Reach",       2, ["Flora", "Light", "Pulse"]),
    ("Zone_PearlseaReef",     "PearlseaReef",       "Pearlsea Reef",       4, ["Frost", "Pulse", "Light"]),
]

# Family mix per zone (counts sum to 200 across all zones).
ZONE_FAMILY_MIX = {
    "Zone_DawnFields":       [("Beast", 4), ("Avian", 3), ("Flora", 3), ("Insectoid", 2), ("Construct", 1), ("Spirit", 1), ("Elemental", 1), ("Dragon", 1)],
    "Zone_DuskMarsh":        [("Flora", 3), ("Beast", 2), ("Insectoid", 3), ("Spirit", 2), ("Aquatic", 2), ("Dragon", 1), ("Elemental", 2), ("Avian", 2)],
    "Zone_EmberRidge":       [("Dragon", 4), ("Elemental", 3), ("Beast", 2), ("Construct", 2), ("Insectoid", 1), ("Spirit", 2), ("Flora", 1), ("Avian", 2)],
    "Zone_Frostveil":        [("Beast", 3), ("Dragon", 2), ("Elemental", 3), ("Avian", 2), ("Construct", 1), ("Spirit", 1), ("Aquatic", 2), ("Flora", 3)],
    "Zone_Glimmerwood":      [("Spirit", 3), ("Construct", 2), ("Flora", 2), ("Beast", 2), ("Insectoid", 2), ("Avian", 1), ("Elemental", 2), ("Dragon", 3)],
    "Zone_HollowApproach":   [("Spirit", 4), ("Dragon", 2), ("Beast", 2), ("Construct", 2), ("Elemental", 1), ("Ancient", 2), ("Insectoid", 2), ("Flora", 2)],
    "Zone_AzureShallows":    [("Aquatic", 7), ("Elemental", 2), ("Beast", 1), ("Avian", 1), ("Dragon", 1), ("Spirit", 1), ("Construct", 2), ("Flora", 2)],
    "Zone_TidebreakerIsles": [("Aquatic", 4), ("Avian", 3), ("Dragon", 2), ("Beast", 1), ("Construct", 1), ("Spirit", 1), ("Elemental", 2), ("Ancient", 3)],
    "Zone_SunscarDesert":    [("Beast", 3), ("Insectoid", 3), ("Elemental", 2), ("Construct", 2), ("Dragon", 1), ("Spirit", 2), ("Avian", 2), ("Flora", 2)],
    "Zone_Stormcrest":       [("Beast", 3), ("Dragon", 3), ("Construct", 2), ("Elemental", 2), ("Avian", 1), ("Ancient", 2), ("Spirit", 2), ("Insectoid", 2)],
    "Zone_VerdantReach":     [("Flora", 4), ("Insectoid", 3), ("Beast", 2), ("Spirit", 1), ("Dragon", 1), ("Construct", 1), ("Avian", 3), ("Elemental", 2)],
    "Zone_PearlseaReef":     [("Aquatic", 6), ("Elemental", 2), ("Spirit", 2), ("Dragon", 1), ("Ancient", 2), ("Construct", 2), ("Beast", 1), ("Flora", 2)],
}

# ---------------------------------------------------------------------------
# Family design kits: body plans, size weights, roles, personality pools,
# activity patterns, work affinities, stat multipliers, diet and loot.
# ---------------------------------------------------------------------------
FAMILIES = {
    "Beast": {
        "plans": ["Quadruped", "Quadruped", "Biped"],
        "sizes": ["Small", "Medium", "Medium", "Large"],
        "role": "Base",
        "personalities": ["Curious", "Loyal", "Energetic", "Social", "Brave"],
        "activity": ["Diurnal", "Diurnal", "Crepuscular"],
        "work": ["Gathering", "Transport"],
        "hp": 1.0, "atk": 1.0, "def": 1.0, "spd": 1.0,
        "prefixes": ["Moss", "Dawn", "Dusk", "Ember", "Rime", "Gale", "Thorn", "River", "Stone", "Hollow", "Sun", "Tide", "Bramble", "Cloud", "Marsh", "Dune"],
        "suffixes": ["paw", "horn", "hide", "runner", "stomper", "whisker", "howl", "tuft", "mane", "hoof", "prowler", "lurker"],
        "tints": [(0.62, 0.50, 0.38), (0.55, 0.45, 0.35), (0.70, 0.58, 0.42), (0.48, 0.40, 0.33)],
        "loot": [("Item_RawMeat", 2), ("Item_Fiber", 2), ("Item_Wood", 2), ("Item_Stone", 2)],
        "diet": ["Item_Berry", "Item_RawMeat", "Item_CookedMeat", "Item_FeedMix"],
    },
    "Dragon": {
        "plans": ["Quadruped", "Serpent", "Avian"],
        "sizes": ["Medium", "Large", "Large", "Huge"],
        "role": "Combat",
        "personalities": ["Brave", "Aggressive", "Independent", "Protective"],
        "activity": ["Diurnal", "Crepuscular", "Nocturnal"],
        "work": ["Defense", "PowerGeneration"],
        "hp": 1.25, "atk": 1.2, "def": 1.1, "spd": 0.95,
        "prefixes": ["Ember", "Frost", "Storm", "Ash", "Glimmer", "Tide", "Dune", "Void", "Dawn", "Magma", "Abyss", "Coral", "Rime", "Verdant", "Sun", "Thunder"],
        "suffixes": ["wing", "fang", "drake", "wyrm", "maw", "crest", "talon", "scale", "spine", "claw", "sovereign", "tyrant"],
        "tints": [(0.85, 0.35, 0.25), (0.30, 0.45, 0.85), (0.55, 0.30, 0.75), (0.90, 0.55, 0.20)],
        "loot": [("Item_CrystalShard", 2), ("Item_DawnShard", 1), ("Item_VoltCore", 1), ("Item_EmberAsh", 2)],
        "diet": ["Item_CookedMeat", "Item_RawMeat", "Item_Berry"],
    },
    "Construct": {
        "plans": ["Biped", "Crystalline", "Quadruped"],
        "sizes": ["Small", "Medium", "Large"],
        "role": "Base",
        "personalities": ["Loyal", "Independent", "Lazy"],
        "activity": ["Diurnal"],
        "work": ["Mining", "Crafting", "PowerGeneration", "Construction"],
        "hp": 1.15, "atk": 0.9, "def": 1.25, "spd": 0.85,
        "prefixes": ["Iron", "Brass", "Runed", "Clockwork", "Glass", "Stone", "Copper", "Resonant", "Piston", "Gear", "Chime", "Lattice"],
        "suffixes": ["golem", "sentinel", "automaton", "warden", "crawler", "tender", "mender", "hauler", "keeper", "drudge"],
        "tints": [(0.60, 0.60, 0.65), (0.72, 0.62, 0.42), (0.50, 0.58, 0.62)],
        "loot": [("Item_Stone", 3), ("Item_CrystalShard", 2), ("Item_Resonator", 1), ("Item_DuneGlass", 2)],
        "diet": ["Item_EnergyCell", "Item_CrystalShard", "Item_FeedMix"],
    },
    "Spirit": {
        "plans": ["Floating", "Amorphous", "Serpent"],
        "sizes": ["Tiny", "Small", "Medium"],
        "role": "Support",
        "personalities": ["Curious", "Timid", "Social", "Independent"],
        "activity": ["Nocturnal", "Nocturnal", "Crepuscular"],
        "work": ["ResearchAssist", "Cooking"],
        "hp": 0.8, "atk": 0.85, "def": 0.75, "spd": 1.1,
        "prefixes": ["Hollow", "Dusk", "Whisper", "Pale", "Wisp", "Mourning", "Silent", "Faded", "Lantern", "Veil", "Ghost", "Ember"],
        "suffixes": ["shade", "veil", "haunt", "mote", "echo", "wraith", "lament", "drift", "sigh", "gleam"],
        "tints": [(0.65, 0.60, 0.90), (0.55, 0.85, 0.80), (0.80, 0.70, 0.95)],
        "loot": [("Item_DawnShard", 1), ("Item_CrystalShard", 1), ("Item_Resonator", 1)],
        "diet": ["Item_Berry", "Item_Dawnbloom", "Item_WarmBroth"],
    },
    "Elemental": {
        "plans": ["Amorphous", "Floating", "Crystalline"],
        "sizes": ["Small", "Medium", "Large"],
        "role": "Combat",
        "personalities": ["Aggressive", "Independent", "Energetic"],
        "activity": ["Diurnal", "Nocturnal"],
        "work": ["PowerGeneration", "Defense"],
        "hp": 1.0, "atk": 1.15, "def": 0.95, "spd": 1.0,
        "prefixes": ["Cinder", "Glacier", "Volt", "Bloom", "Zephyr", "Magma", "Rime", " Static", "Pyre", "Frost", "Gale", "Bloom"],
        "suffixes": ["blaze", "shard", "surge", "bloom", "vortex", "heart", "core", "storm", "veil", "crown"],
        "tints": [(0.90, 0.45, 0.25), (0.45, 0.75, 0.95), (0.55, 0.90, 0.45)],
        "loot": [("Item_EmberAsh", 2), ("Item_VoltCore", 1), ("Item_Frostbloom", 1), ("Item_EnergyCell", 1)],
        "diet": ["Item_CrystalShard", "Item_EnergyCell", "Item_Berry"],
    },
    "Aquatic": {
        "plans": ["Serpent", "Amorphous", "Quadruped"],
        "sizes": ["Small", "Medium", "Large"],
        "role": "Support",
        "personalities": ["Curious", "Social", "Timid", "Energetic"],
        "activity": ["Diurnal", "Crepuscular"],
        "work": ["Gathering", "Transport"],
        "hp": 1.0, "atk": 0.9, "def": 1.05, "spd": 1.05,
        "prefixes": ["Tide", "Coral", "Pearl", "Abyss", "Reef", "Kelp", "Brine", "Lagoon", "Undertow", "Salt", "Wave", "Drift"],
        "suffixes": ["fin", "gill", "ray", "crest", "jelly", "skimmer", "nymph", "song", "maw", "shell", "tide", "splash"],
        "tints": [(0.30, 0.65, 0.80), (0.45, 0.80, 0.75), (0.25, 0.50, 0.75)],
        "loot": [("Item_SeaPearl", 1), ("Item_CoralShard", 2), ("Item_RawMeat", 2)],
        "diet": ["Item_RawMeat", "Item_Berry", "Item_CookedMeat"],
    },
    "Insectoid": {
        "plans": ["Insectoid", "Insectoid", "Quadruped"],
        "sizes": ["Tiny", "Small", "Medium"],
        "role": "Base",
        "personalities": ["Energetic", "Social", "Independent"],
        "activity": ["Diurnal", "Crepuscular", "Nocturnal"],
        "work": ["Gathering", "Farming"],
        "hp": 0.85, "atk": 0.95, "def": 1.1, "spd": 1.15,
        "prefixes": ["Chitin", "Dust", "Thorn", "Gilded", "Hive", "Reed", "Sand", "Bark", "Mud", "Spore", "Glimmer", "Wire"],
        "suffixes": ["mite", "weevil", "hornet", "scarab", "crawler", "spine", "wing", "grub", "strid", "burrower"],
        "tints": [(0.55, 0.50, 0.30), (0.40, 0.55, 0.30), (0.65, 0.55, 0.25)],
        "loot": [("Item_Fiber", 3), ("Item_Fertilizer", 1), ("Item_ChitinPlate", 2)],
        "diet": ["Item_Berry", "Item_FeedMix", "Item_Dawnbloom"],
    },
    "Flora": {
        "plans": ["Quadruped", "Amorphous", "Biped"],
        "sizes": ["Small", "Medium", "Large"],
        "role": "Base",
        "personalities": ["Lazy", "Curious", "Loyal", "Social"],
        "activity": ["Diurnal"],
        "work": ["Farming", "Gathering"],
        "hp": 1.1, "atk": 0.85, "def": 1.15, "spd": 0.8,
        "prefixes": ["Fern", "Bough", "Bramble", "Petal", "Root", "Pollen", "Thorn", "Mycel", "Bloom", "Sap", "Verdant", "Orchid"],
        "suffixes": ["bloom", "sprout", "thorn", "bough", "fern", "vine", "husk", "bulb", "frond", "treant"],
        "tints": [(0.35, 0.65, 0.35), (0.55, 0.75, 0.40), (0.30, 0.55, 0.30)],
        "loot": [("Item_Fiber", 3), ("Item_Berry", 3), ("Item_Fertilizer", 1), ("Item_Dawnbloom", 1)],
        "diet": ["Item_Fertilizer", "Item_Berry", "Item_Dawnbloom"],
    },
    "Avian": {
        "plans": ["Avian", "Avian", "Floating"],
        "sizes": ["Tiny", "Small", "Medium"],
        "role": "Explorer",
        "personalities": ["Curious", "Energetic", "Independent", "Social"],
        "activity": ["Diurnal", "Crepuscular"],
        "work": ["Transport", "ResearchAssist"],
        "hp": 0.8, "atk": 0.9, "def": 0.8, "spd": 1.25,
        "prefixes": ["Gale", "Plume", "Sky", "Dawn", "Storm", "Reef", "Sun", "Mist", "Comet", "Down", "Thermal", "Crest"],
        "suffixes": ["wing", "plume", "song", "talon", "beak", "cry", "flutter", "glider", "raptor", "kestrel"],
        "tints": [(0.85, 0.75, 0.45), (0.55, 0.65, 0.95), (0.90, 0.60, 0.50)],
        "loot": [("Item_Fiber", 2), ("Item_Dawnbloom", 1), ("Item_DawnShard", 1)],
        "diet": ["Item_Berry", "Item_RawMeat", "Item_FeedMix"],
    },
    "Ancient": {
        "plans": ["Crystalline", "Biped", "Floating"],
        "sizes": ["Large", "Huge"],
        "role": "Combat",
        "personalities": ["Independent", "Protective", "Brave"],
        "activity": ["Nocturnal", "Diurnal"],
        "work": ["ResearchAssist", "PowerGeneration"],
        "hp": 1.4, "atk": 1.3, "def": 1.3, "spd": 0.8,
        "prefixes": ["Prime", "Monolith", "Astral", "Forgotten", "Elder", "Relic", "Vesper", "Hallowed"],
        "suffixes": ["colossus", "monolith", "primarch", "reliquary", "warden", "sentinel", "custodian", "effigy"],
        "tints": [(0.80, 0.65, 0.95), (0.65, 0.85, 0.80), (0.90, 0.80, 0.55)],
        "loot": [("Item_AncientCore", 1), ("Item_DawnShard", 2), ("Item_CrystalShard", 3)],
        "diet": ["Item_EnergyCell", "Item_AncientCore", "Item_CrystalShard"],
    },
}

# Fix a stray space typo defensively.
for fam in FAMILIES.values():
    fam["prefixes"] = [p.strip() for p in fam["prefixes"]]

SIZE_STATS = {
    "Tiny":   {"hp": 40,  "atk": 6,  "def": 3,  "spd": 520, "cap": 0.00, "sight": 900},
    "Small":  {"hp": 70,  "atk": 10, "def": 6,  "spd": 480, "cap": 0.05, "sight": 1200},
    "Medium": {"hp": 110, "atk": 16, "def": 10, "spd": 420, "cap": 0.12, "sight": 1500},
    "Large":  {"hp": 170, "atk": 24, "def": 15, "spd": 360, "cap": 0.20, "sight": 1900},
    "Huge":   {"hp": 260, "atk": 34, "def": 21, "spd": 300, "cap": 0.28, "sight": 2400},
}

FAMILY_CAPTURE_BONUS = {"Dragon": 0.10, "Ancient": 0.15, "Elemental": 0.05}
HOSTILE_FAMILIES = {"Dragon", "Spirit", "Elemental", "Ancient"}

# Extra zone-flavored loot items (registered in BuildItems alongside this table).
ZONE_LOOT = {
    "Zone_AzureShallows": ("Item_SeaPearl", 1),
    "Zone_TidebreakerIsles": ("Item_SeaPearl", 1),
    "Zone_PearlseaReef": ("Item_CoralShard", 2),
    "Zone_SunscarDesert": ("Item_DuneGlass", 2),
    "Zone_Stormcrest": ("Item_StormSilver", 1),
}

SILHOUETTE = {
    "Quadruped": "four-legged body, low head, tail",
    "Biped": "upright stance, forward arms, crest",
    "Serpent": "coiling spine, wedge head, fin-tail",
    "Floating": "hovering core, drifting motes, no legs",
    "Insectoid": "segmented shell, twin antennae, four spindly legs",
    "Avian": "keeled chest, folded wings, beaked head",
    "Crystalline": "faceted shards, luminous seams, geometric crown",
    "Amorphous": "flowing mass, embedded lights, no fixed shape",
}


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def build_species():
    """Deterministic roster assembly. Returns list of dicts."""
    species = []
    used_names = set()
    used_ids = set()

    for zone_idx, (zone_id, zone_enum, zone_name, threat, elements) in enumerate(ZONES):
        mix = ZONE_FAMILY_MIX[zone_id]
        element_cursor = 0
        for fam_name, count in mix:
            kit = FAMILIES[fam_name]
            for i in range(count):
                # --- deterministic pickers ---
                plan = kit["plans"][i % len(kit["plans"])]
                size = kit["sizes"][i % len(kit["sizes"])]
                element = elements[element_cursor % len(elements)]
                element_cursor += 1
                personality = kit["personalities"][i % len(kit["personalities"])]
                activity = kit["activity"][i % len(kit["activity"])]
                role = kit["role"]

                # --- name: prefix pool x suffix pool, index-rotated, deduped ---
                name = None
                for attempt in range(64):
                    p = kit["prefixes"][(i + attempt * 3 + zone_idx) % len(kit["prefixes"])]
                    s = kit["suffixes"][(i + attempt * 5) % len(kit["suffixes"])]
                    cand = p + s
                    if cand not in used_names:
                        name = cand
                        break
                if name is None:  # extremely unlikely fallback
                    name = f"{fam_name}{zone_idx}{i}"
                used_names.add(name)

                sp_id = f"Echo_{name}"
                if sp_id in used_ids:
                    sp_id = f"Echo_{name}{zone_idx}"
                used_ids.add(sp_id)

                # --- stats ---
                base = SIZE_STATS[size]
                threat_mult = 0.85 + 0.15 * threat  # t1=1.0 .. t4=1.45
                hp = round(base["hp"] * threat_mult * kit["hp"], 1)
                atk = round(base["atk"] * threat_mult * kit["atk"], 1)
                dfn = round(base["def"] * threat_mult * kit["def"], 1)
                spd = round(base["spd"] * kit["spd"], 0)

                # --- capture difficulty ---
                cap = base["cap"] + 0.12 * (threat - 1) + FAMILY_CAPTURE_BONUS.get(fam_name, 0.0)
                cap = round(clamp(cap, 0.2, 0.95), 2)

                # --- hostility: hostile lineages in wilder zones ---
                hostile = (fam_name in HOSTILE_FAMILIES and threat >= 3 and (i % 3) != 0) or \
                          (threat >= 4 and fam_name in ("Beast", "Insectoid") and (i % 2) == 0)

                # --- appearance tints (family palette + index variation) ---
                pr, pg, pb = kit["tints"][i % len(kit["tints"])]
                var = ((i * 7) % 5 - 2) * 0.02
                pr = round(clamp(pr + var, 0.05, 0.95), 3)
                pg = round(clamp(pg - var, 0.05, 0.95), 3)
                pb = round(clamp(pb + var * 0.5, 0.05, 0.95), 3)
                # secondary: darker, hue-shifted
                sr = round(clamp(pr * 0.55 + 0.10, 0.05, 0.9), 3)
                sg = round(clamp(pg * 0.55 + 0.05, 0.05, 0.9), 3)
                sb = round(clamp(pb * 0.55 + 0.20, 0.05, 0.9), 3)

                # --- diet / loot ---
                diet = [kit["diet"][i % len(kit["diet"])]]
                if i % 2 == 1 and len(kit["diet"]) > 1:
                    diet.append(kit["diet"][(i + 1) % len(kit["diet"])])

                loot_a = kit["loot"][i % len(kit["loot"])]
                loot_b = kit["loot"][(i + 2) % len(kit["loot"])]
                if zone_id in ZONE_LOOT and (i % 2 == 0):
                    loot_b = ZONE_LOOT[zone_id]

                work_a = kit["work"][i % len(kit["work"])]
                work_b = kit["work"][(i + 1) % len(kit["work"])]

                species.append({
                    "id": sp_id, "name": name, "family": fam_name, "plan": plan,
                    "size": size, "element": element, "weakness": WEAK_TO[element],
                    "role": role, "zone_id": zone_id, "zone_enum": zone_enum,
                    "zone_name": zone_name, "threat": threat,
                    "personality": personality, "activity": activity,
                    "hp": hp, "atk": atk, "def": dfn, "spd": spd,
                    "cap": cap, "hostile": hostile,
                    "pr": pr, "pg": pg, "pb": pb, "sr": sr, "sg": sg, "sb": sb,
                    "diet": diet, "loot": [loot_a, loot_b],
                    "work": [work_a, work_b],
                    "sight": base["sight"],
                })
    return species


def emit_cpp(species):
    """Emit the generated C++ registration table (single %% -> literal %)."""
    lines = []
    a = lines.append
    a("// ===========================================================================")
    a("// AstrawildBestiaryData.cpp")
    a("//")
    a(f"// {GENERATION_NOTE}")
    a("//")
    a("// The Grand Menagerie: %d generated species across all 12 zones. Each row" % len(species))
    a("// feeds UAstrawildEchoDefinition including the Batch 8 appearance fields")
    a("// (family/body plan/size/tints) so every species renders a distinct")
    a("// procedural silhouette at runtime (AAstrawildEchoCharacter::BuildProceduralBody).")
    a("// ===========================================================================")
    a("")
    a('#include "AstrawildBestiaryData.h"')
    a("")
    a('#include "AstrawildDataAssets.h"')
    a('#include "AstrawildItemRegistrySubsystem.h"')
    a('#include "AstrawildLog.h"')
    a('#include "AstrawildZoneSubsystem.h"')
    a("")
    a("namespace")
    a("{")
    a("    struct FBestiaryRow")
    a("    {")
    a("        const TCHAR* Id;")
    a("        const TCHAR* Name;")
    a("        EAstrawildEchoFamily Family;")
    a("        EAstrawildBodyPlan BodyPlan;")
    a("        EAstrawildSizeClass SizeClass;")
    a("        EAstrawildElementType Element;")
    a("        EAstrawildElementType Weakness;")
    a("        EAstrawildEchoRole Role;")
    a("        EAstrawildZone HomeZone;")
    a("        FName HomeZoneId;")
    a("        EAstrawildPersonality Personality;")
    a("        EAstrawildActivityPattern Activity;")
    a("        float HP;")
    a("        float ATK;")
    a("        float DEF;")
    a("        float Speed;")
    a("        float CaptureDifficulty;")
    a("        bool bHostile;")
    a("        float PrimaryR, PrimaryG, PrimaryB;")
    a("        float SecondaryR, SecondaryG, SecondaryB;")
    a("        const TCHAR* FoodA;")
    a("        const TCHAR* FoodB;")
    a("        const TCHAR* LootA; int32 LootAQ;")
    a("        const TCHAR* LootB; int32 LootBQ;")
    a("        EAstrawildWorkType WorkA;")
    a("        EAstrawildWorkType WorkB;")
    a("        float SightRadius;")
    a("        float WorkAffinityA;")
    a("    };")
    a("")
    a("    static const FBestiaryRow Rows[] = {")

    for s in species:
        food_b = s["diet"][1] if len(s["diet"]) > 1 else "nullptr"
        food_b_cpp = f'TEXT("{food_b}")' if food_b != "nullptr" else "nullptr"
        # work affinity strength: family-native work gets 1.4, secondary 1.0
        aff = 1.4 if s["threat"] >= 3 else 1.2
        a("        { TEXT(\"%s\"), TEXT(\"%s\")," % (s["id"], s["name"]))
        a("            EAstrawildEchoFamily::%s, EAstrawildBodyPlan::%s, EAstrawildSizeClass::%s," % (s["family"], s["plan"], s["size"]))
        a("            EAstrawildElementType::%s, EAstrawildElementType::%s," % (s["element"], s["weakness"]))
        a("            EAstrawildEchoRole::%s, EAstrawildZone::%s, TEXT(\"%s\")," % (s["role"], s["zone_enum"], s["zone_id"]))
        a("            EAstrawildPersonality::%s, EAstrawildActivityPattern::%s," % (s["personality"], s["activity"]))
        a("            %.1ff, %.1ff, %.1ff, %.0ff, %.2ff, %s," % (s["hp"], s["atk"], s["def"], s["spd"], s["cap"], "true" if s["hostile"] else "false"))
        a("            %.3ff, %.3ff, %.3ff, %.3ff, %.3ff, %.3ff," % (s["pr"], s["pg"], s["pb"], s["sr"], s["sg"], s["sb"]))
        a("            TEXT(\"%s\"), %s," % (s["diet"][0], food_b_cpp))
        a("            TEXT(\"%s\"), %d, TEXT(\"%s\"), %d," % (s["loot"][0][0], s["loot"][0][1], s["loot"][1][0], s["loot"][1][1]))
        a("            EAstrawildWorkType::%s, EAstrawildWorkType::%s, %.0ff, %.1ff }," % (s["work"][0], s["work"][1], s["sight"], aff))

    a("    };")
    a("")
    a("    constexpr int32 RowCount = static_cast<int32>(sizeof(Rows) / sizeof(Rows[0]));")
    a("")
    a("    FAstrawildItemStack MakeStack(const FName ItemId, const int32 Quantity)")
    a("    {")
    a("        FAstrawildItemStack Stack;")
    a("        Stack.ItemId = ItemId;")
    a("        Stack.Quantity = Quantity;")
    a("        return Stack;")
    a("    }")
    a("")
    a("    FAstrawildWorkAffinity MakeAffinity(const EAstrawildWorkType Type, const float Rate)")
    a("    {")
    a("        FAstrawildWorkAffinity Affinity;")
    a("        Affinity.WorkType = Type;")
    a("        Affinity.Affinity = Rate;")
    a("        return Affinity;")
    a("    }")
    a("")
    a("    const TCHAR* GetSilhouettePhrase(const EAstrawildBodyPlan Plan)")
    a("    {")
    a("        switch (Plan)")
    a("        {")
    a("        case EAstrawildBodyPlan::Quadruped:  return TEXT(\"Four-legged frame with a low-set head\");")
    a("        case EAstrawildBodyPlan::Biped:      return TEXT(\"Upright stance with a forward crest\");")
    a("        case EAstrawildBodyPlan::Serpent:    return TEXT(\"Coiling spine and a wedge head\");")
    a("        case EAstrawildBodyPlan::Floating:   return TEXT(\"Hovering core wreathed in drifting motes\");")
    a("        case EAstrawildBodyPlan::Insectoid:  return TEXT(\"Segmented shell on four spindly legs\");")
    a("        case EAstrawildBodyPlan::Avian:      return TEXT(\"Keeled chest and folded wings\");")
    a("        case EAstrawildBodyPlan::Crystalline:return TEXT(\"Faceted shards with luminous seams\");")
    a("        case EAstrawildBodyPlan::Amorphous:  return TEXT(\"A flowing mass pierced by steady lights\");")
    a("        default:                             return TEXT(\"A strange silhouette\");")
    a("        }")
    a("    }")
    a("")
    a("    const TCHAR* GetElementPhrase(const EAstrawildElementType Element)")
    a("    {")
    a("        switch (Element)")
    a("        {")
    a("        case EAstrawildElementType::Light:  return TEXT(\"light\");")
    a("        case EAstrawildElementType::Ash:    return TEXT(\"ash\");")
    a("        case EAstrawildElementType::Flora:  return TEXT(\"flora\");")
    a("        case EAstrawildElementType::Ember:  return TEXT(\"ember\");")
    a("        case EAstrawildElementType::Frost:  return TEXT(\"frost\");")
    a("        case EAstrawildElementType::Pulse:  return TEXT(\"pulse\");")
    a("        default:                            return TEXT(\"wild\");")
    a("        }")
    a("    }")
    a("")
    a("    FString DescribeRow(const FBestiaryRow& Row)")
    a("    {")
    a("        const FAstrawildZoneDescriptor* ZoneDesc = UAstrawildZoneSubsystem::FindZoneById(Row.HomeZoneId);")
    a("        const FString ZoneName = ZoneDesc ? ZoneDesc->DisplayName.ToString() : TEXT(\"the Vale\");")
    a("        return FString::Printf(TEXT(\"%s of the %s. %s, tuned to %s resonance.\"),")
    a("            Row.Name, *ZoneName, GetSilhouettePhrase(Row.BodyPlan), GetElementPhrase(Row.Element));")
    a("    }")
    a("}")
    a("")
    a("// ---- public API (see AstrawildBestiaryData.h) ----")
    a("")
    a("void AstrawildBestiary::RegisterAll(UAstrawildItemRegistrySubsystem* Registry)")
    a("{")
    a("    if (!Registry)")
    a("    {")
    a("        return;")
    a("    }")
    a("")
    a("    int32 Registered = 0;")
    a("    int32 CodexIndex = 11; // 1-10 are the hand-authored Batch 1-7 species.")
    a("    for (const FBestiaryRow& Row : Rows)")
    a("    {")
    a("        UAstrawildEchoDefinition* Echo = NewObject<UAstrawildEchoDefinition>(Registry);")
    a("        Echo->DefinitionId = Row.Id;")
    a("        Echo->DisplayName = FText::FromString(Row.Name);")
    a("        Echo->Description = FText::FromString(DescribeRow(Row));")
    a("        Echo->Element = Row.Element;")
    a("        Echo->Role = Row.Role;")
    a("        Echo->BaseStats.MaxHealth = Row.HP;")
    a("        Echo->BaseStats.AttackPower = Row.ATK;")
    a("        Echo->BaseStats.Defense = Row.DEF;")
    a("        Echo->BaseStats.MoveSpeed = Row.Speed;")
    a("        Echo->BaseStats.CaptureResilience = FMath::Clamp(Row.CaptureDifficulty * 0.8f, 0.05f, 0.95f);")
    a("        Echo->DominantPersonality = Row.Personality;")
    a("        Echo->ActivityPattern = Row.Activity;")
    a("        Echo->PreferredFoodIds.Add(Row.FoodA);")
    a("        if (Row.FoodB)")
    a("        {")
    a("            Echo->PreferredFoodIds.Add(Row.FoodB);")
    a("        }")
    a("        Echo->CaptureDifficulty = Row.CaptureDifficulty;")
    a("        Echo->WeaknessElement = Row.Weakness;")
    a("        Echo->bHostileToPlayers = Row.bHostile;")
    a("        Echo->TrustGainOnCapture = 10.0f;")
    a("        Echo->SightRadius = Row.SightRadius;")
    a("        Echo->LoseSightRadius = Row.SightRadius * 1.5f;")
    a("        Echo->HabitatBiomeIds.Add(Row.HomeZoneId);")
    a("        Echo->DefeatLoot.Add(MakeStack(Row.LootA, Row.LootAQ));")
    a("        Echo->DefeatLoot.Add(MakeStack(Row.LootB, Row.LootBQ));")
    a("        Echo->WorkAffinities.Add(MakeAffinity(Row.WorkA, Row.WorkAffinityA));")
    a("        Echo->WorkAffinities.Add(MakeAffinity(Row.WorkB, 1.0f));")
    a("        Echo->Family = Row.Family;")
    a("        Echo->BodyPlan = Row.BodyPlan;")
    a("        Echo->SizeClass = Row.SizeClass;")
    a("        Echo->PrimaryTint = FLinearColor(Row.PrimaryR, Row.PrimaryG, Row.PrimaryB, 1.0f);")
    a("        Echo->SecondaryTint = FLinearColor(Row.SecondaryR, Row.SecondaryG, Row.SecondaryB, 1.0f);")
    a("        Echo->HomeZone = Row.HomeZone;")
    a("        Echo->CodexIndex = CodexIndex++;")
    a("        Registry->RegisterEcho(Echo);")
    a("        ++Registered;")
    a("    }")
    a("")
    a("    UE_LOG(LogAstrawildEconomy, Log, TEXT(\"Bestiary registered: %d generated species across 12 zones.\"), Registered);")
    a("}")
    a("")
    a("int32 AstrawildBestiary::GetRowCount()")
    a("{")
    a("    return RowCount;")
    a("}")
    a("")
    a("void AstrawildBestiary::ValidateTable(TArray<FString>& OutProblems)")
    a("{")
    a("    OutProblems.Reset();")
    a("    TSet<FName> SeenIds;")
    a("    TSet<FName> SeenZones;")
    a("    for (int32 Index = 0; Index < RowCount; ++Index)")
    a("    {")
    a("        const FBestiaryRow& Row = Rows[Index];")
    a("        const FName Id(Row.Id);")
    a("        if (Id == NAME_None || SeenIds.Contains(Id))")
    a("        {")
    a("            OutProblems.Add(FString::Printf(TEXT(\"Row %d: duplicate or missing id (%s).\"), Index, Row.Id));")
    a("        }")
    a("        SeenIds.Add(Id);")
    a("        SeenZones.Add(Row.HomeZoneId);")
    a("        if (Row.HP <= 0.0f || Row.ATK <= 0.0f || Row.DEF < 0.0f || Row.Speed <= 0.0f)")
    a("        {")
    a("            OutProblems.Add(FString::Printf(TEXT(\"Row %d (%s): non-positive stat.\"), Index, Row.Id));")
    a("        }")
    a("        if (Row.CaptureDifficulty < 0.2f || Row.CaptureDifficulty > 0.95f)")
    a("        {")
    a("            OutProblems.Add(FString::Printf(TEXT(\"Row %d (%s): capture difficulty out of range.\"), Index, Row.Id));")
    a("        }")
    a("        if (Row.Element == Row.Weakness)")
    a("        {")
    a("            OutProblems.Add(FString::Printf(TEXT(\"Row %d (%s): weakness equals element.\"), Index, Row.Id));")
    a("        }")
    a("        if (!UAstrawildZoneSubsystem::FindZoneById(Row.HomeZoneId))")
    a("        {")
    a("            OutProblems.Add(FString::Printf(TEXT(\"Row %d (%s): unknown home zone id.\"), Index, Row.Id));")
    a("        }")
    a("    }")
    a("    if (SeenZones.Num() != 12)")
    a("    {")
    a("        OutProblems.Add(FString::Printf(TEXT(\"Table covers %d zones, expected 12.\"), SeenZones.Num()));")
    a("    }")
    a("}")
    a("")
    return "\n".join(lines)


ELEMENT_TH = {
    "Light": "แสง", "Ash": "เถ้า", "Flora": "พฤกษชาติ", "Ember": "เพลิง", "Frost": "น้ำแข็ง", "Pulse": "สายฟ้า",
}
FAMILY_TH = {
    "Beast": "สัตว์ร้าง", "Dragon": "มังกร", "Construct": "หุ่นยนต์โบราณ", "Spirit": "วิญญาณ",
    "Elemental": "ธาตุวิญญาณ", "Aquatic": "อสูรน้ำ", "Insectoid": "แมลงยักษ์", "Flora": "พฤกษอสูร",
    "Avian": "นกอสูร", "Ancient": "โบราณสถานเทวะ",
}


def emit_doc(species):
    """Emit the designed codex markdown (mirrors the C++ table 1:1)."""
    lines = []
    a = lines.append
    a("# ASTRAWILD — The Grand Menagerie Codex (Batch 8)")
    a("")
    a(f"> {GENERATION_NOTE}  ")
    a("> Mirror of `Source/AstrawildCore/Private/AstrawildBestiaryData.cpp` — one table, two artifacts.")
    a("")
    a("## ภาพรวมสายพันธุ์ (Roster Overview)")
    a("")
    a(f"- **{len(species)} generated species + 10 hand-authored species = {len(species) + 10} Echo species ทั้งหมด** (และ NPC 12 ตัวใน 2 หมู่บ้าน = ตัวละครรวม {len(species) + 10 + 12}+)")
    a("- ทุกตัวมีดีไซน์ครบ: ตระกูล (Family), โครงร่าง (BodyPlan), ขนาด (SizeClass), สีหลัก-สีรอง (tints 2 สี), ธาตุ, จุดอ่อน, บุคลิก, ช่วงเวลา active, อาหาร, loot, งานในฐาน (work affinity), ความยากในการจับ และโซนที่อยู่อาศัย")
    a("- ธาตุ: 3 คู่ตรงข้าม — แสง↔เถ้า, พฤกษชาติ↔เพลิง, น้ำแข็ง↔สายฟ้า (จุดอ่อนคือคู่ตรงข้าม ×1.5)")
    a("- สถิติสเกลตาม ขนาด × ระดับอันตรายของโซน × ตัวคูณตระกูล (มังกร/โบราณแกร่งกว่า)")
    a("- ระบบ AI เดิม (perception + state machine + personality + activity pattern) ทำงานกับทุกสายพันธุ์ทันที — data-driven 100%")
    a("")
    a("| ตระกูล | คำอธิบาย | โครงร่าง | งานที่ถนัด |")
    a("|---|---|---|---|")
    FAMILY_TABLE = [
        ("Beast", "สัตว์ร้างทั่วไป เชื่องง่าย เลี้ยงง่าย", "Gathering/Transport"),
        ("Dragon", "มังกรแท้ โจมตีสูง จับยาก ตัวท็อปของแต่ละโซน", "Defense/PowerGeneration"),
        ("Construct", "หุ่นยนต์โบราณ ตัวเกราะ เก็บแร่/ประกอบ/ผลิตไฟ", "Mining/Crafting/Power/Construction"),
        ("Spirit", "วิญญาณ ออกหากินตอนกลางคืน เก็บงานวิจัย/ทำอาหาร", "ResearchAssist/Cooking"),
        ("Elemental", "ธาตุวิญญาณบริสุทธิ์ โจมตีธาตุแรง ผลิตพลังงาน", "PowerGeneration/Defense"),
        ("Aquatic", "อสูรน้ำของ 3 โซนทะเล/เกาะ/แนวปะการัง", "Gathering/Transport"),
        ("Insectoid", "แมลงยักษ์ เร็ว ทำงานเก็บของ/ทำฟาร์ม", "Gathering/Farming"),
        ("Flora", "พฤกษอสูร ตัวแน่น ทำฟาร์มเก่งสุด", "Farming/Gathering"),
        ("Avian", "นกอสูร เร็วมาก สำรวจ/ขนของ", "Transport/ResearchAssist"),
        ("Ancient", "เทวะโบราณ หายาก แกร่งสุด (โซนอันตรายสูง)", "ResearchAssist/PowerGeneration"),
    ]
    for fam, desc, work in FAMILY_TABLE:
        a(f"| **{fam}** ({FAMILY_TH[fam]}) | {desc} | {'/'.join(FAMILIES[fam]['plans'])} | {work} |")
    a("")
    a("## สรุปตามโซน (Zone Compendium)")
    a("")
    by_zone = {}
    for s in species:
        by_zone.setdefault(s["zone_name"], []).append(s)
    for zone_id, zone_enum, zone_name, threat, _ in ZONES:
        rows = by_zone.get(zone_name, [])
        a(f"### {zone_name} — Threat {threat} ({len(rows)} species)")
        a("")
        a("| # | Species | ตระกูล | โครงร่าง | ขนาด | ธาตุ | อ่อนแอต่อ | HP/ATK/DEF/SPD | จับยาก | ดุร้าย | อาหาร | Loot |")
        a("|---|---|---|---|---|---|---|---|---|---|---|---|")
        for i, s in enumerate(sorted(rows, key=lambda r: r["id"])):
            hostile = "⚠ ดุ" if s["hostile"] else "สงบ"
            a("| %d | **%s** | %s | %s | %s | %s | %s | %.0f/%.0f/%.0f/%.0f | %.2f | %s | %s | %s×%d + %s×%d |" % (
                i + 1, s["name"], s["family"], s["plan"], s["size"],
                ELEMENT_TH[s["element"]], ELEMENT_TH[s["weakness"]],
                s["hp"], s["atk"], s["def"], s["spd"], s["cap"], hostile,
                ", ".join(d.replace("Item_", "") for d in s["diet"]),
                s["loot"][0][0].replace("Item_", ""), s["loot"][0][1],
                s["loot"][1][0].replace("Item_", ""), s["loot"][1][1],
            ))
        a("")
    # family coverage summary
    fams = {}
    for s in species:
        fams[s["family"]] = fams.get(s["family"], 0) + 1
    a("## สรุปจำนวนตามตระกูล")
    a("")
    a("| ตระกูล | จำนวน |")
    a("|---|---|")
    for fam, count in sorted(fams.items(), key=lambda kv: -kv[1]):
        a(f"| {fam} ({FAMILY_TH[fam]}) | {count} |")
    a("")
    a("## การใช้งานในเกม (Integration)")
    a("")
    a("- **สัตว์ป่าในโลก**: `AAstrawildWorldBootstrapper` เลือก signature species ประจำโซนวางสปอนตาม `HomeZone` — ดูตาราง `ZoneWildlife` ใน bootstrapper")
    a("- **รูปร่างหน้าตา**: `AAstrawildEchoCharacter::BuildProceduralBody()` ประกอบร่างจาก BodyPlan + SizeClass + tints — ไม่ต้องมี art asset ก็แยกออกทันที")
    a("- **AI**: ทุกตัววิ่งบน `AAstrawildEchoAIController` เดิม (perception + บุคลิก + activity pattern + weather) — กลางคืน Spirit จะออกล่า กลางวัน Beast เดินหาอาหาร")
    a("- **การจับ**: `CaptureComponent` ใช้ CaptureDifficulty + เลือดน้อย + อาหารที่ชอบ + สภาพอากาศตามระบบเดิม")
    a("- **งานฐาน**: work affinities เสียบ `WorkSiteActor` ระบบเดิม — Construct เก็บแร่, Flora ทำฟาร์ม, Elemental ผลิตไฟ")
    a("- **บอส**: โซน Tidebreaker Isles ใช้ `Echo_Dawnfang` (มังกรน้ำ Serpent Large) เป็นบอสดันเจียนที่ 2 — Sunken Vault")
    a("")
    return "\n".join(lines)


def main():
    species = build_species()
    print(f"Generated {len(species)} species across {len(ZONES)} zones.")
    assert 200 <= len(species) <= 220, f"Roster drifted outside 200..220, got {len(species)}"
    ids = [s["id"] for s in species]
    names = [s["name"] for s in species]
    assert len(set(ids)) == len(ids), "Duplicate species ids!"
    assert len(set(names)) == len(names), "Duplicate species names!"
    by_zone = {}
    for s in species:
        by_zone.setdefault(s["zone_name"], 0)
        by_zone[s["zone_name"]] += 1
    for z, c in by_zone.items():
        print(f"  {z}: {c}")
    elems = {}
    for s in species:
        elems[s["element"]] = elems.get(s["element"], 0) + 1
    print("  elements:", elems)
    fams = {}
    for s in species:
        fams[s["family"]] = fams.get(s["family"], 0) + 1
    print("  families:", fams)

    cpp = emit_cpp(species)
    with open(CPP_OUT, "w", encoding="utf-8") as f:
        f.write(cpp)
    print(f"Wrote {CPP_OUT} ({len(cpp.splitlines())} lines)")

    doc = emit_doc(species)
    with open(DOC_OUT, "w", encoding="utf-8") as f:
        f.write(doc)
    print(f"Wrote {DOC_OUT} ({len(doc.splitlines())} lines)")


if __name__ == "__main__":
    main()
