#!/usr/bin/env python3
"""
ASTRAWILD — Sci-Fantasy Mutation Spec generator (SCI-FANTASY DIRECTIVE, Phase 1/2).

Generates:
  1. Source/AstrawildCore/Private/AstrawildEchoMutationData.cpp
     (204 FEchoMutationSpec rows — one per generated bestiary species)
  2. Docs/ASTRAWILD_SCI_FANTASY_THEMES.md
     (theme roster: counts, rules, base-mesh mapping, mutation vocabulary)

Design contract (SCI-FANTASY MONSTER ACQUISITION & GENERATION DIRECTIVE):
  - The 204 bestiary species are regrouped into 8 Sci-Fantasy visual themes
    (Ancient Constructs, Elemental Beasts, Mutated Fauna, Armored Organics,
    Ethereal Spirits, Mechanical Hybrids, Plant Monsters, Void Abominations).
  - Every species gets a FEchoMutationSpec: base mesh id (one of 16 baked
    archetype bases), per-part scale multipliers, an attachment mask, a
    material theme, a pattern tint, a VFX type and a sound-set id.
  - Deterministic: same input -> same output (name-hash jitter, index math
    only, no RNG). Species data is parsed from the ACTUAL
    AstrawildBestiaryData.cpp table (never hand-copied).
  - UAstrawildEchoMutator (C++) consumes this table at runtime; the spec is
    applied on top of BOTH the procedural PMC body and the skinned base path
    (opt-in, fail-closed, PMC fallback always intact).

Run:  python3 Scripts/generate_echo_mutations.py
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CPP_OUT = os.path.join(ROOT, "Source", "AstrawildCore", "Private", "AstrawildEchoMutationData.cpp")
DOC_OUT = os.path.join(ROOT, "Docs", "ASTRAWILD_SCI_FANTASY_THEMES.md")
BESTIARY = os.path.join(ROOT, "Source", "AstrawildCore", "Private", "AstrawildBestiaryData.cpp")

GENERATION_NOTE = "Generated by Scripts/generate_echo_mutations.py (Sci-Fantasy directive) - DO NOT EDIT BY HAND. Re-run the script instead."

# ---------------------------------------------------------------------------
# 8 Sci-Fantasy themes (directive Phase 1.1) — replaces the visual grouping
# axis (BodyPlan stays the PMC silhouette kit; THEME owns the identity).
# ---------------------------------------------------------------------------
THEMES = [
    "AncientConstruct", "ElementalBeast", "MutatedFauna", "ArmoredOrganic",
    "EtherealSpirit", "MechanicalHybrid", "PlantMonster", "VoidAbomination",
]

# Strong name-keyword signals (checked in priority order).
KEYWORDS = {
    "VoidAbomination": ["void", "abyss", "shadow", "gloom", "dusk", "hollow", "murk",
                        "undertow", "brine", "deep", "night", "dark", "shade"],
    "MechanicalHybrid": ["volt", "gear", "piston", "arc", "circuit", "spark", "coil",
                         "mech", "chrome", "steel", "bolt", "engine", "dyna", "charge"],
    "AncientConstruct": ["golem", "monolith", "coloss", "relic", "ancient", "stone",
                         "ruin", "granite", "prime", "elder", "hallow", "vesper", "primarch"],
    "PlantMonster": ["moss", "bloom", "fern", "spore", "thorn", "bramble", "sprig",
                     "flora", "root", "vine", "seed", "mush", "petal", "leaf", "verdant",
                     "coral", "reed", "bough", "canopy"],
    "EtherealSpirit": ["ghost", "spirit", "wisp", "phantom", "specter", "soul", "wail",
                       "lume", "mist", "glimmer", "dream", "aura", "chime"],
    "ElementalBeast": ["ember", "pyre", "flame", "blaze", "magma", "frost", "rime",
                       "glacier", "gale", "storm", "thunder", "tide", "wave", "current",
                       "sun", "dawn", "ray", "melt", "freeze"],
    "ArmoredOrganic": ["shell", "plate", "carapace", "scale", "chitin", "bastion",
                       "bulwark", "shield", "armor", "crest", "horn", "beetle", "crab"],
}

# Family default theme (no keyword hit).
FAMILY_DEFAULT = {
    "Construct": "AncientConstruct", "Ancient": "AncientConstruct",
    "Spirit": "EtherealSpirit", "Elemental": "ElementalBeast",
    "Flora": "PlantMonster", "Insectoid": "ArmoredOrganic",
    "Beast": "MutatedFauna", "Avian": "MutatedFauna",
    "Dragon": "MutatedFauna", "Aquatic": "MutatedFauna",
}

# 16 base archetypes (two per theme) — baked by Tools/ArtSourceGen/gen_sci_fantasy_bases.py.
BASES = {
    "AncientConstruct": {"primary": "SK_Base_GolemQuadruped", "secondary": "SK_Base_MonolithColossus"},
    "ElementalBeast": {"primary": "SK_Base_ElemDrake", "secondary": "SK_Base_ElemWisp"},
    "MutatedFauna": {"primary": "SK_Base_MutantBeast", "secondary": "SK_Base_MutantAvian"},
    "ArmoredOrganic": {"primary": "SK_Base_ArmoredBeetle", "secondary": "SK_Base_ArmoredCrab"},
    "EtherealSpirit": {"primary": "SK_Base_SpiritWisp", "secondary": "SK_Base_SpiritOrb"},
    "MechanicalHybrid": {"primary": "SK_Base_CyborgBeast", "secondary": "SK_Base_CyborgSerpent"},
    "PlantMonster": {"primary": "SK_Base_PlantMaw", "secondary": "SK_Base_Mushroomling"},
    "VoidAbomination": {"primary": "SK_Base_VoidBlob", "secondary": "SK_Base_VoidTentacle"},
}

# Body-plan buckets -> primary/secondary base preference.
PLAN_BUCKET = {
    "quadruped": "primary", "biped": "primary", "insectoid": "primary",
    "crystalline": "primary",
    "avian": "secondary", "floating": "secondary",
    "serpent": "secondary", "amorphous": "secondary",
}

# Material theme per Sci-Fantasy theme.
MATERIAL_THEME = {
    "AncientConstruct": "Stony", "ElementalBeast": "Energy", "MutatedFauna": "Organic",
    "ArmoredOrganic": "Chitin", "EtherealSpirit": "Energy", "MechanicalHybrid": "Metallic",
    "PlantMonster": "Organic", "VoidAbomination": "Slime",
}
# Crystalline bodies read as crystal regardless of theme.
CRYSTAL_OVERRIDE = "Crystalline"
VOID_MATERIAL = "Void"

# Element -> persistent VFX type (directive Phase 2 VFX Binding vocabulary).
ELEMENT_VFX = {
    "Ember": "Fire", "Frost": "Frost", "Pulse": "Electric", "Flora": "Spore",
    "Light": "Radiant", "Ash": "Poison",
}

# Attachment bits (must mirror EAstrawildEchoAttachment in AstrawildEchoMutator.h).
ATTACH_BITS = {
    "DorsalSpikes": 1, "Wings": 2, "ThirdEye": 4, "ExtraArms": 8,
    "HornCrown": 16, "GlowNodes": 32, "TailFin": 64,
}
# Theme attachment bias (deterministic picks come from this list).
ATTACH_BIAS = {
    "AncientConstruct": ["HornCrown", "GlowNodes", "DorsalSpikes"],
    "ElementalBeast": ["GlowNodes", "Wings", "DorsalSpikes"],
    "MutatedFauna": ["DorsalSpikes", "ThirdEye", "ExtraArms", "Wings"],
    "ArmoredOrganic": ["DorsalSpikes", "HornCrown", "TailFin"],
    "EtherealSpirit": ["GlowNodes", "Wings"],
    "MechanicalHybrid": ["ExtraArms", "GlowNodes", "ThirdEye"],
    "PlantMonster": ["DorsalSpikes", "ThirdEye", "ExtraArms"],
    "VoidAbomination": ["ExtraArms", "ThirdEye", "GlowNodes", "Wings"],
}

# Theme identity tints (pattern color base; jittered per species deterministically).
THEME_TINTS = {
    "AncientConstruct": (0.62, 0.58, 0.50),
    "ElementalBeast": (0.95, 0.62, 0.30),
    "MutatedFauna": (0.55, 0.48, 0.38),
    "ArmoredOrganic": (0.45, 0.52, 0.42),
    "EtherealSpirit": (0.72, 0.82, 0.95),
    "MechanicalHybrid": (0.58, 0.63, 0.70),
    "PlantMonster": (0.42, 0.71, 0.33),
    "VoidAbomination": (0.38, 0.30, 0.44),
}


def spec_hash(name: str) -> int:
    h = 2166136261
    for ch in name:
        h = (h * 16777619) ^ ord(ch)
    return h & 0x7FFFFFFF


def jitter(seed: int, salt: int, spread: float, lo: float) -> float:
    v = ((seed >> (salt * 7)) % 1024) / 1023.0
    return lo + v * spread


def clamp01(c):
    return tuple(max(0.0, min(1.0, float(x))) for x in c)


# ---------------------------------------------------------------------------
# Parse the actual bestiary table (same provenance pattern as gen_tier_b.py).
# ---------------------------------------------------------------------------
def parse_bestiary() -> list:
    with open(BESTIARY, encoding="utf-8") as fh:
        src = fh.read()
    rows = re.findall(
        r'\{ TEXT\("(Echo_\w+)"\), TEXT\("(\w+)"\),\s*'
        r'EAstrawildEchoFamily::(\w+), EAstrawildBodyPlan::(\w+), EAstrawildSizeClass::(\w+),\s*'
        r'EAstrawildElementType::(\w+), EAstrawildElementType::(\w+),',
        src)
    out = []
    for (rid, name, fam, plan, size, elem, weak) in rows:
        out.append({
            "id": rid, "name": name, "family": fam, "plan": plan,
            "size": size, "element": elem, "weakness": weak,
        })
    return out


# ---------------------------------------------------------------------------
# Theme assignment (deterministic, priority-ordered).
# ---------------------------------------------------------------------------
def assign_theme(row: dict) -> str:
    name = row["name"].lower()
    fam = row["family"]
    plan = row["plan"].lower()

    # 1) strong name keywords (priority order matters).
    for theme in ("VoidAbomination", "MechanicalHybrid", "AncientConstruct",
                  "PlantMonster", "EtherealSpirit", "ElementalBeast", "ArmoredOrganic"):
        for kw in KEYWORDS[theme]:
            if kw in name:
                return theme

    # 2) body-plan overrides: amorphous blobs twist into Void unless they are
    #    flora/spirits; crystalline shards read as ancient constructs.
    if plan == "amorphous" and fam not in ("Flora", "Spirit"):
        return "VoidAbomination"
    if plan == "crystalline":
        return "AncientConstruct"

    # 3) family default.
    return FAMILY_DEFAULT.get(fam, "MutatedFauna")


def assign_base(theme: str, plan: str) -> str:
    bucket = PLAN_BUCKET.get(plan, "primary")
    return BASES[theme][bucket]


def assign_material(theme: str, plan: str) -> str:
    if plan.lower() == "crystalline":
        return CRYSTAL_OVERRIDE
    if theme == "VoidAbomination" and plan.lower() == "amorphous":
        return VOID_MATERIAL
    return MATERIAL_THEME[theme]


def assign_vfx(element: str, theme: str) -> str:
    if element in ELEMENT_VFX:
        return ELEMENT_VFX[element]
    if theme == "VoidAbomination":
        return "Void"
    return "None"


def assign_attachments(theme: str, plan: str, seed: int) -> int:
    bias = ATTACH_BIAS[theme]
    count = 1 + (seed % 3)  # 1..3 deterministic attachments
    mask = 0
    for i in range(count):
        pick = bias[(seed >> (4 + i * 3)) % len(bias)]
        mask |= ATTACH_BITS[pick]
    # Flight-capable bodies earn wings more often; ground bodies never get
    # wings from the bias alone (directive: "ปีกเกิน" is a mutant signature).
    if plan.lower() in ("avian", "floating", "serpent") and (seed % 4 == 0):
        mask |= ATTACH_BITS["Wings"]
    return mask


def assign_scales(seed: int):
    # Per-part scale multipliers in [0.75, 1.45] (deterministic per species).
    head = jitter(seed, 1, 0.70, 0.75)
    torso = jitter(seed, 2, 0.60, 0.80)
    limb = jitter(seed, 3, 0.55, 0.80)
    tail = jitter(seed, 4, 0.65, 0.70)
    return round(head, 3), round(torso, 3), round(limb, 3), round(tail, 3)


def assign_pattern_tint(theme: str, seed: int):
    base = THEME_TINTS[theme]
    r = clamp01((base[0] + jitter(seed, 5, 0.24, -0.12),))
    g = clamp01((base[1] + jitter(seed, 6, 0.24, -0.12),))
    b = clamp01((base[2] + jitter(seed, 7, 0.24, -0.12),))
    return r[0], g[0], b[0]


def build_specs(rows: list) -> list:
    specs = []
    for row in rows:
        theme = assign_theme(row)
        plan = row["plan"].lower()
        seed = spec_hash(row["name"])
        head, torso, limb, tail = assign_scales(seed)
        mask = assign_attachments(theme, plan, seed)
        tint = assign_pattern_tint(theme, seed)
        specs.append({
            "id": row["id"], "theme": theme,
            "base": assign_base(theme, plan),
            "head": head, "torso": torso, "limb": limb, "tail": tail,
            "mask": mask,
            "material": assign_material(theme, plan),
            "tint": tint,
            "vfx": assign_vfx(row["element"], theme),
            "sound": "SFXSet_" + theme,
            "family": row["family"], "plan": plan, "element": row["element"],
        })
    return specs


# ---------------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------------
def emit_cpp(specs: list) -> str:
    L = []
    a = L.append
    a("// ===========================================================================")
    a("// AstrawildEchoMutationData.cpp")
    a("//")
    a(f"// {GENERATION_NOTE}")
    a("//")
    a("// Sci-Fantasy Directive Phase 2: the FEchoMutationSpec table — one row per")
    a("// generated bestiary species (204). Parsed from the ACTUAL")
    a("// AstrawildBestiaryData.cpp rows at generation time (never hand-copied).")
    a("// Consumed by UAstrawildEchoMutator::FindSpec; applies on top of the PMC")
    a("// procedural body AND the skinned base-mesh path (opt-in, fail-closed).")
    a("// ===========================================================================")
    a("")
    a('#include "AstrawildEchoMutator.h"')
    a("")
    a("namespace AstrawildEchoMutation")
    a("{")
    a("    const TArray<FEchoMutationSpec>& GetMutationSpecs()")
    a("    {")
    a(f"        static const TArray<FEchoMutationSpec> Rows =")
    a("        {")
    for s in specs:
        a("            {")
        a(f'                TEXT("{s["id"]}"),')
        a(f"                EAstrawildSciFantasyTheme::{s['theme']},")
        a(f'                TEXT("{s["base"]}"),')
        a(f"                {s['head']}f, {s['torso']}f, {s['limb']}f, {s['tail']}f,")
        a(f"                0x{s['mask']:08X},")
        a(f"                EAstrawildMutationMaterialTheme::{s['material']},")
        a(f"                FLinearColor({s['tint'][0]:.3f}f, {s['tint'][1]:.3f}f, {s['tint'][2]:.3f}f, 1.0f),")
        a(f"                EAstrawildEchoVfxType::{s['vfx']},")
        a(f'                TEXT("{s["sound"]}")')
        a("            },")
    a("        };")
    a("        return Rows;")
    a("    }")
    a("}")
    a("")
    return "\n".join(L)


def emit_doc(specs: list) -> str:
    L = []
    a = L.append
    theme_counts = {}
    base_counts = {}
    vfx_counts = {}
    mat_counts = {}
    for s in specs:
        theme_counts[s["theme"]] = theme_counts.get(s["theme"], 0) + 1
        base_counts[s["base"]] = base_counts.get(s["base"], 0) + 1
        vfx_counts[s["vfx"]] = vfx_counts.get(s["vfx"], 0) + 1
        mat_counts[s["material"]] = mat_counts.get(s["material"], 0) + 1
    # diversity signature check (mirrors the automation test)
    sigs = set()
    for s in specs:
        bucket = lambda v: int(v * 4)  # 4 scale buckets per axis
        sigs.add((s["theme"], s["base"], bucket(s["head"]), bucket(s["torso"]),
                  bucket(s["limb"]), s["mask"], s["material"], s["vfx"]))

    a("# ASTRAWILD — Sci-Fantasy Theme Roster & Mutation System (Directive SCI)")
    a("")
    a(f"> {GENERATION_NOTE}  ")
    a("> Data mirror: `Source/AstrawildCore/Private/AstrawildEchoMutationData.cpp` (204 rows) +")
    a("> `UAstrawildEchoMutator` (runtime application). Base meshes: `Tools/ArtSourceGen/gen_sci_fantasy_bases.py`.")
    a("")
    a("## 8 ธีม Sci-Fantasy (จัดกลุ่มใหม่จาก 204 สายพันธุ์)")
    a("")
    a("| ธีม | คำอธิบาย | สายพันธุ์ | Material | ฐานโมเดล (2/ธีม) |")
    a("|---|---|---|---|---|")
    THEME_DESC = {
        "AncientConstruct": "หุ่นยนต์หิน/โลหะโบราณ โกเลม เครื่องจักรยุคดึกดำบรรพ์",
        "ElementalBeast": "สัตว์ธาตุ ร่างไฟ/น้ำแข็ง/พลังงาน + Particle VFX ติดตัว",
        "MutatedFauna": "สัตว์กลายพันธุ์ หลายหัว หนาม ปีกเกิน ตาเดียว",
        "ArmoredOrganic": "สิ่งมีชีวิตสวมเกราะ/กระดอง แมลงยักษ์ ปูหุ้มเกราะ",
        "EtherealSpirit": "วิญญาณ ผี สิ่งมีชีวิตโปร่งแสงลอยได้",
        "MechanicalHybrid": "สัตว์กึ่งหุ่นยนต์ มีสายไฟ ขดลวด ชิ้นส่วนโลหะ",
        "PlantMonster": "พืชกินคน ดอกไม้ยักษ์ เห็ดมีชีวิต",
        "VoidAbomination": "อสูรมิติอื่น ร่างบิดเบี้ยว ไร้รูปทรงแน่นอน",
    }
    for t in THEMES:
        a(f"| **{t}** | {THEME_DESC[t]} | {theme_counts.get(t, 0)} | {MATERIAL_THEME[t]} | {BASES[t]['primary']}, {BASES[t]['secondary']} |")
    a("")
    a(f"**รวม {len(specs)} สายพันธุ์ / 8 ธีม / 16 ฐานโมเดล** — signature ไม่ซ้ำ {len(sigs)}/{len(specs)} "
      f"(bucket scale × attachments × material × vfx — เกณฑ์ automation ≥ 170)")
    a("")
    a("## ระบบ Mutation (Phase 2)")
    a("")
    a("- **Per-part scale:** หัว/ลำตัว/ขา/หาง ย่อ-ขยายไม่เท่ากัน ([0.75, 1.45] ต่อแกน, deterministic จากชื่อ)")
    a("- **Attachment mask (7 ชนิด):** DorsalSpikes / Wings / ThirdEye / ExtraArms / HornCrown / GlowNodes / TailFin")
    a("- **Material theme (8):** Metallic / Stony / Energy / Slime / Chitin / Organic / Crystalline / Void")
    a("- **Pattern tint:** สีลายสุ่มอิสระจากสีพื้น (ธีม palette + deterministic jitter)")
    a("- **VFX type (8):** Fire / Frost / Electric / Void / Poison / Spore / Radiant / None — ผูกกับธาตุ")
    a("")
    a("### VFX distribution")
    a("")
    a("| VfxType | จำนวน | | Material | จำนวน |")
    a("|---|---|---|---|---|")
    vkeys = sorted(vfx_counts, key=lambda k: -vfx_counts[k])
    mkeys = sorted(mat_counts, key=lambda k: -mat_counts[k])
    for i in range(max(len(vkeys), len(mkeys))):
        v = f"{vkeys[i]} {vfx_counts[vkeys[i]]}" if i < len(vkeys) else ""
        m = f"{mkeys[i]} {mat_counts[mkeys[i]]}" if i < len(mkeys) else ""
        a(f"| {v} | | {m} |")
    a("")
    a("### Base mesh distribution")
    a("")
    a("| BaseMeshId | จำนวน |")
    a("|---|---|")
    for b in sorted(base_counts, key=lambda k: -base_counts[k]):
        a(f"| {b} | {base_counts[b]} |")
    a("")
    a("## ตัวอย่าง 20 สายพันธุ์แรก")
    a("")
    a("| Species | ธีม | ฐาน | Head/Torso/Limb/Tail | Attachments | Material | VFX |")
    a("|---|---|---|---|---|---|---|")
    def mask_names(mask):
        names = [n for n, b in ATTACH_BITS.items() if mask & b]
        return ", ".join(names) if names else "—"
    for s in specs[:20]:
        a(f"| {s['id']} | {s['theme']} | {s['base']} | {s['head']}/{s['torso']}/{s['limb']}/{s['tail']} | {mask_names(s['mask'])} | {s['material']} | {s['vfx']} |")
    a("")
    a("## ความสัมพันธ์กับระบบเดิม")
    a("")
    a("- BodyPlan เดิมยังใช้เป็น PMC silhouette kit (fallback เมื่อโมเดลฐานยังไม่ import)")
    a("- ธีมคือแกน visual identity ใหม่ — ใช้ทั้งบน PMC (vertex color + สัดส่วน) และ skinned base mesh")
    a("- 6 hero species + Tier-B 39 ตัว: spec ได้จาก BuildDeterministicSpec (ตารางนี้เก็บเฉพาะ 204 bestiary rows)")
    a("- Fallback สุดท้าย: procedural primitive ผสม (PMC เดิม + การกลายพันธุ์) — ไม่มีสายพันธุ์ไหนตัน")
    return "\n".join(L)


def main():
    rows = parse_bestiary()
    assert len(rows) == 204, f"Expected 204 bestiary rows, parsed {len(rows)}"
    specs = build_specs(rows)
    ids = [s["id"] for s in specs]
    assert len(set(ids)) == 204, "Duplicate species ids in mutation table!"

    # Every theme must be represented (directive: 8 groups, none empty).
    themes = {s["theme"] for s in specs}
    assert themes == set(THEMES), f"Theme coverage gap: {set(THEMES) - themes}"

    # Attachment mask sanity: never zero, never all-bits.
    for s in specs:
        assert 0 < s["mask"] <= 0x7F, f"Bad mask {s['mask']} for {s['id']}"
        for v in (s["head"], s["torso"], s["limb"], s["tail"]):
            assert 0.7 <= v <= 1.5, f"Scale out of range for {s['id']}: {v}"

    counts = {}
    for s in specs:
        counts[s["theme"]] = counts.get(s["theme"], 0) + 1
    print(f"[sci-fantasy] {len(specs)} specs across {len(counts)} themes: {counts}")

    cpp = emit_cpp(specs)
    with open(CPP_OUT, "w", encoding="utf-8") as f:
        f.write(cpp)
    print(f"Wrote {CPP_OUT} ({len(cpp.splitlines())} lines)")

    doc = emit_doc(specs)
    with open(DOC_OUT, "w", encoding="utf-8") as f:
        f.write(doc)
    print(f"Wrote {DOC_OUT} ({len(doc.splitlines())} lines)")


if __name__ == "__main__":
    main()
