"""Generate the checked-in Unreal Gameplay Tag registry for ASTRAWILD source/data."""
from __future__ import annotations

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Config/DefaultGameplayTags.ini"
TAG_PATTERN = re.compile(r"\b[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z0-9_]+)+\b")
STRING_TAG_PATTERN = re.compile(r"[\"']([A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z0-9_]+)+)[\"']")
BACKTICK_TAG_PATTERN = re.compile(r"`([A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z0-9_]+)+)`")
ALLOWED_ROOTS = {
    "Ability",
    "Activity",
    "Biome",
    "Building",
    "Buff",
    "Camp",
    "Capture",
    "Cooking",
    "Damage",
    "Diet",
    "Element",
    "Encounter",
    "Echo",
    "Effect",
    "Food",
    "Frame",
    "Group",
    "Hazard",
    "Harvest",
    "Interact",
    "Item",
    "Location",
    "Mecha",
    "Mount",
    "MountWeapon",
    "Partner",
    "PartnerGear",
    "Profile",
    "Quest",
    "Recipe",
    "Region",
    "Skill",
    "Spire",
    "Station",
    "Status",
    "System",
    "Technology",
    "Trait",
    "Tower",
    "VFX",
    "Weapon",
    "WorldEvent",
    "Work",
}


def add_allowed(tags: set[str], candidate: str) -> None:
    if candidate.split(".", 1)[0] in ALLOWED_ROOTS:
        tags.add(candidate)


def collect_tags() -> set[str]:
    tags: set[str] = set()

    # C++ tags are only accepted from quoted literals. This deliberately avoids
    # treating member access such as Ability.BaseDamage as a gameplay tag.
    for path in (ROOT / "Source").rglob("*"):
        if path.is_file() and path.suffix.lower() in {".h", ".cpp"}:
            text = path.read_text(encoding="utf-8", errors="replace")
            for match in STRING_TAG_PATTERN.findall(text):
                add_allowed(tags, match)

    # CSV cells are data contracts, so scan their complete values.
    csv_root = ROOT / "Content/Astrawild/Data/Source"
    for path in csv_root.glob("*.csv"):
        with path.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.reader(handle):
                for value in row:
                    for match in TAG_PATTERN.findall(value):
                        add_allowed(tags, match)

    # Documentation contributes only explicitly formatted inline tags.
    for path in (ROOT / "Docs").rglob("*.md"):
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in BACKTICK_TAG_PATTERN.findall(text):
            add_allowed(tags, match)

    return tags


def write_registry(tags: set[str]) -> None:
    lines = [
        "; Generated by Scripts/generate_gameplay_tag_registry.py. Keep this file under source control.",
        "; Tags are project data contracts; rename only with a save/data migration.",
        "[/Script/GameplayTags.GameplayTagsSettings]",
        "ImportTagsFromConfig=True",
    ]
    lines.extend(f'+GameplayTagList=(Tag="{tag}",DevComment="ASTRAWILD source/data contract")' for tag in sorted(tags))
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    tags = collect_tags()
    if not tags:
        print("No ASTRAWILD gameplay tags found; registry was not written.")
        return 1
    write_registry(tags)
    print(f"Generated {OUTPUT.relative_to(ROOT)} with {len(tags)} gameplay tags.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
